title: Yoojin Oh # your name (or website title) here
logo: "/images/yoojinoh_profile_2.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate student - Major in Artificial Intelligence
  <br>
  <a href="https://pai.ewha.ac.kr/">Ewha Womans University PAI LAB</a>
  <br><br>
  <a href="https://drive.google.com/file/d/1yPjSPdN36mwIlMj13IbcDPfj4pbvPvYI/view?usp=sharing"View My Curriculum Vitae</a>
  <br>
  <a href="https://www.linkedin.com/in/yoojin-oh-228991262/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
